version: '3.3'

services:

  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: ./Dockerfile
      args:
        - ELK_VERSION=${ELK_VERSION}
    ports:
      - "$ELASTIC_PORT:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://elastic:$ELASTIC_PASSWORD@localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 100
    expose:
      - "9300"
      - "9200"
    volumes:
      - "./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    networks:
      - elk

  kibana:
    build:
      context: ./docker/kibana
      dockerfile: ./Dockerfile
      args:
        - ELK_VERSION=${ELK_VERSION}
    ports:
      - "$KIBANA_PORT:5601"
    volumes:
      - "./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    networks:
      - elk
    depends_on:
      elasticsearch:
          condition: service_healthy

networks:
  elk:
    driver: bridge