version: '3.3'

services:

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
      args:
        - ELK_VERSION=${ELK_VERSION}
    ports:
      - "$ELASTIC_PORT:9200"
    expose:
      - "9300"
      - "9200"
    volumes:
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  kibana:
    build:
      context: ./kibana
      dockerfile: ./Dockerfile
      args:
        - ELK_VERSION=${ELK_VERSION}
    ports:
      - "$KIBANA_PORT:5601"
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    networks:
      - elk

networks:
  elk:
    driver: bridge